version: '3.0'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports: 
      - 8001:5000
    extra_hosts:
    - 'host.docker.internal:host-gateway'
    volumes:
      - .:/app
    depends_on:
      - db
  
  queue:
    build: 
      context: . 
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on: 
      - db      

  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 3367:3306 